In [1]:
import pandas as pd

In [72]:
movie_data = pd.read_excel('data/movie.metadata.xlsx')
character_data = pd.read_excel('data/character.metadata.xlsx')

In [73]:
movie_data['Year'] = movie_data['Movie release date'].astype(str).str[:4]
character_data['Year'] = character_data['Movie release date'].astype(str).str[:4]
display(movie_data.sort_values(by=['Year']).head(10))
display(character_data.sort_values(by=['Year']).head(10))

,Wikipedia movie ID,Freebase movie ID,Movie name,Movie release date,Movie box office revenue,Movie runtime,Movie languages (Freebase ID:name tuples),Movie countries (Freebase ID:name tuples),Movie genres (Freebase ID:name tuples),Year
0,29666067,/m/0fphzrf,Hunting Season,1010-12-02,12160978.0,140.0,"{""/m/02hwyss"": ""Turkish Language"", ""/m/02h40lc...","{""/m/01znc_"": ""Turkey""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/02n4kr"": ""My...",1010
74,1082508,/m/044ggd,Roundhay Garden Scene,1888,NaN,0.03,"{""/m/06ppq"": ""Silent film""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/02hmvc"": ""Short Film"", ""/m/06ppq"": ""Silen...",1888
75,12170539,/m/02vs8rb,"Leisurely Pedestrians, Open Topped Buses and H...",1889,NaN,NaN,"{""/m/06ppq"": ""Silent film"", ""/m/02h40lc"": ""Eng...","{""/m/07ssc"": ""United Kingdom""}","{""/m/02hmvc"": ""Short Film"", ""/m/06ppq"": ""Silen...",1889
76,6431996,/m/0g53t3,"Monkeyshines, No. 1",1890,NaN,NaN,"{""/m/06ppq"": ""Silent film""}","{""/m/09c7w0"": ""United States of America""}","{""/m/06ppq"": ""Silent film""}",1890
77,22770416,/m/0gj9h_4,London's Trafalgar Square,1890,NaN,NaN,"{""/m/06ppq"": ""Silent film""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/02hmvc"": ""Short Film"", ""/m/06ppq"": ""Silen...",1890
78,32175981,/m/0gy0t95,Men Boxing,1891,NaN,0.0833333333333,"{""/m/06ppq"": ""Silent film""}",{},"{""/m/02hmvc"": ""Short Film"", ""/m/06ppq"": ""Silen...",1891
79,27773121,/m/0cc8h1v,Newark Athlete,1891,NaN,0.2,{},{},"{""/m/02hmvc"": ""Short Film""}",1891
80,644824,/m/02_1qn,Dickson Greeting,1891,NaN,0.05,{},"{""/m/09c7w0"": ""United States of America""}","{""/m/02hmvc"": ""Short Film"", ""/m/0219x_"": ""Indie""}",1891
3,6431647,/m/0g53g2,Pauvre Pierrot,1892-10-28,NaN,NaN,"{""/m/06ppq"": ""Silent film""}","{""/m/0f8l9c"": ""France""}","{""/m/02hmvc"": ""Short Film"", ""/m/06ppq"": ""Silen...",1892
2,9996498,/m/02pz844,Le Clown et ses chiens,1892-10-28,NaN,NaN,"{""/m/06ppq"": ""Silent film""}","{""/m/0f8l9c"": ""France""}","{""/m/02hmvc"": ""Short Film"", ""/m/06ppq"": ""Silen...",1892

,Wikipedia movie ID,Freebase movie ID,Movie release date,Character name,Actor date of birth,Actor gender,Actor height (in meters),Actor ethnicity (Freebase ID),Actor name,Actor age at movie release,Freebase character/actor map ID,Freebase character ID,Freebase actor ID,Year
67633,29666067,/m/0fphzrf,1010-12-02,Murat Önes,NaN,M,NaN,NaN,Mahir Ipek,NaN,/m/0n4fvtw,/m/0n4fvtz,/m/0n4fvv5,1010
67631,29666067,/m/0fphzrf,1010-12-02,Hatun,NaN,F,NaN,NaN,Nergis Çorakçi,NaN,/m/0n4ftj1,/m/0n4ftj4,/m/0n4ftjc,1010
67630,29666067,/m/0fphzrf,1010-12-02,Asit Omer,NaN,M,NaN,NaN,Riza Kocaoglu,NaN,/m/0n4fssj,/m/0n4fssm,/m/0n4fssv,1010
67629,29666067,/m/0fphzrf,1010-12-02,Asiye,1985-07-06 00:00:00,F,NaN,NaN,Melisa Sözen,NaN,/m/0k3m4yc,/m/0n4fs00,/m/0ch3v_t,1010
67628,29666067,/m/0fphzrf,1010-12-02,Battal,1945-07-16 00:00:00,M,NaN,NaN,Çetin Tekindor,NaN,/m/0h9dtmf,/m/0n4frvc,/m/0ch5v5f,1010
67627,29666067,/m/0fphzrf,1010-12-02,Hasan,1978-12-13 00:00:00,M,NaN,NaN,Okan Yalabık,NaN,/m/0ggd8h0,/m/0n4fsc3,/m/0cmb83k,1010
67626,29666067,/m/0fphzrf,1010-12-02,Idris,1973-04-23 00:00:00,M,NaN,NaN,Cem Yılmaz,NaN,/m/0gb33kn,/m/0n4flr2,/m/0fz9xn,1010
67625,29666067,/m/0fphzrf,1010-12-02,Ferman,1941-12-26 00:00:00,M,NaN,NaN,Şener Şen,NaN,/m/0gb33kh,/m/0n4fgzm,/m/02z247j,1010
67624,29666067,/m/0fphzrf,1010-12-02,Kamuran,1983,M,NaN,NaN,Bartu Küçükçaglayan,NaN,/m/0n4fxh5,/m/0n4fxh8,/m/0df0qkt,1010
67634,29666067,/m/0fphzrf,1010-12-02,Hilal,NaN,F,NaN,NaN,Sefika Tolun,NaN,/m/0n4fwp_,/m/0n4fwq2,/m/0n4fwq9,1010

In [75]:
display(movie_data.groupby(by=['Year']))
display(character_data.groupby(by=['Year']).apply(lambda x:len(x)))

/var/folders/gc/k740v3612cv_1m5s2d93wxzr0000gn/T/ipykernel_50619/437534852.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  display(movie_data.groupby(by=['Year']).apply(lambda x:len(x)))

Year
1010       1
1888       1
1889       1
1890       2
1891       3
        ...
2013     164
2014      17
2015       4
2016       3
nan     6902
Length: 131, dtype: int64

/var/folders/gc/k740v3612cv_1m5s2d93wxzr0000gn/T/ipykernel_50619/437534852.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  display(character_data.groupby(by=['Year']).apply(lambda x:len(x)))

Year
1010      15
1888       4
1891       1
1893       2
1894       4
        ...
2013     928
2014      39
2015      14
2016       6
nan     9995
Length: 128, dtype: int64

/var/folders/gc/k740v3612cv_1m5s2d93wxzr0000gn/T/ipykernel_50619/4433505.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  character_data.groupby(by=['Year']).apply(lambda x:len(x))

Year
1894        1
1895        1
1896        4
1897        1
1898        1
        ...
2011    11938
2012     5919
2013      685
2014       28
2016        6
Length: 121, dtype: int64